var defaultItemGrid = [
    [
        "Key_to_Depths_marked",
        "Annex_Key_marked",
        "Archive_Prison_Extra_Key_marked",
        "Archive_Tower_Cell_Key_marked",
        "Key_to_New_Londo_Ruins",
    ],
    [
        "Basement_Key_marked",
        "Blighttown_Key",
        "Cage_Key_marked",
        "Crest_Key",
        "Dungeon_Cell_Key",
        "Mystery_Key_marked",
    ],
    [
        "Residence_Key_marked",
        "Sewer_Chamber_Key",
        "Undead_Asylum_F2_East_Key_marked",
        "Watchtower_Basement_Key_marked",
        "Key_to_the_Seal",
    ],
    [
        "Covenant_of_Artorias",
        "Crest_of_Artorias",
        "Darkmoon_Seance_Ring",
        "Orange_Charred_Ring",
        "Peculiar_doll",
        "Broken_Pendant",
    ],
    [
        "Lordvessel",
        "Bequeathed_Lord_Soul_Shard_Seath_marked",
        "Bequeathed_Lord_Soul_Shard_4K_marked",
        "Lord_Soul_Nito_marked",
        "Lord_Soul_BoC_marked",
    ],
]

var baseItems = {
    Annex_Key_marked: false,
    Archive_Prison_Extra_Key_marked: false,
    Archive_Tower_Cell_Key_marked: false,
    Archive_Tower_Giant_Cell_Key: false,
    Archive_Tower_Giant_Door_Key: false,
    Armor_Smithbox: false,
    Basement_Key_marked: false,
    Bequeathed_Lord_Soul_Shard_4K_marked: false,
    Bequeathed_Lord_Soul_Shard_Seath_marked: false,
    Big_Pilgrims_Key: false,
    blank: false,
    Blighttown_Key: false,
    Bottomless_Box: false,
    Broken_Pendant: false,
    Cage_Key_marked: false,
    Chaos_Flame_Ember: false,
    Covenant_of_Artorias: false,
    Crest_Key: false,
    Crest_of_Artorias: false,
    Crystal_Ember: false,
    Darkmoon_Seance_Ring: false,
    Dark_Ember: false,
    Divine_and_LargeDivine_Ember: 0,
    Dungeon_Cell_Key: false,
    Enchanted_Ember: false,
    Key_to_Depths_marked: false,
    Key_to_New_Londo_Ruins: false,
    Key_to_the_Seal: false,
    Large_and_VeryLarge_Ember: 0,
    Large_Flame_Ember: false,
    Large_Magic_Ember: false,
    Lordvessel: false,
    Lord_Soul_BoC_marked: false,
    Lord_Soul_Nito_marked: false,
    Master_Key: false,
    Mystery_Key_marked: false,
    Orange_Charred_Ring: false,
    Peculiar_doll: false,
    Quelaags_Domain_Bell: false,
    Repairbox: false,
    Residence_Key_marked: false,
    Rite_of_Kindling: false,
    Sewer_Chamber_Key: false,
    Torch: false,
    Undead_Asylum_F2_East_Key_marked: false,
    Undead_Asylum_F2_West_Key_marked: false,
    Undead_Church_Bell: false,
    Watchtower_Basement_Key_marked: false,
    Weapon_Smithbox: false,

    blank: false,
};

var itemsMin = {
    Divine_and_LargeDivine_Ember: 0,
    Large_and_VeryLarge_Ember: 0,
};

var itemsMax = {
    Divine_and_LargeDivine_Ember: 3,
    Large_and_VeryLarge_Ember: 3,
};

var items = Object.assign(baseItems);
